<?php

namespace TMall\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * carte_fideliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class carte_fideliteRepository extends EntityRepository
{
}
