<?php

namespace TMall\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * reclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reclamationRepository extends EntityRepository
{
}
